### ISSUE TITLE
Contact us section with content

### ISSUE THREAD

**Issue by daniduthisum** [VishwaAmarasinghe/codeflow-website#11]
**Is your feature request related to a problem? Please describe.**
Add contact us section to display the content 

**Describe the solution you'd like**
Add section tag with id and content

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by daniduthisum** [comment]
Can you assign me.

**Comment by VishwaAmarasinghe** [comment]
Yeah sure

**Comment by daniduthisum** [comment]
Good.

**Comment by daniduthisum** [comment]
We have another about us issue . So we can change this to complete the contact us

**Comment by VishwaAmarasinghe** [comment]
Yeah that's better
