### ISSUE TITLE
Remove the type.js

### ISSUE THREAD

**Issue by daniduthisum** [VishwaAmarasinghe/codeflow-website#12]
**Is your feature request related to a problem? Please describe.**
In mobile typed js is don't match to website 

**Describe the solution you'd like**
Remove type.js and add normal text file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
Yeah, go ahead. I will assign you.

**Comment by daniduthisum** [comment]
Ok sure
