### ISSUE TITLE
The background image is not showing in home section

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [VishwaAmarasinghe/codeflow-website#13]
**Describe the bug**
There is a background image behind in the home page and it's not showing.

**To Reproduce**
1. Go to https://vishwaamarasinghe.github.io/codeflow-website/
2. See error

**Expected behavior**
The image should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/90438593/156866293-e911c063-6d29-4545-ba17-2da7e97e05d6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
@daniduthisum give your ideas

**Comment by daniduthisum** [comment]
Reupload to github
