### ISSUE TITLE
Add a gif to home page.

### ISSUE THREAD

**Issue by daniduthisum** [VishwaAmarasinghe/codeflow-website#15]
**Is your feature request related to a problem? Please describe.**
Remove jpj image and add gif to home page

**Describe the solution you'd like**
Add gif file to assets/img folder and link it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
In the previous issue and its pr could not fix the bugs in the home page. So use this pr also to fix that bugs

**Comment by VishwaAmarasinghe** [comment]
We have to add a gif file using Github. Not using terminal.

**Comment by VishwaAmarasinghe** [comment]
> We have to add a gif file using Github. Not using terminal.

I will add that gif file using main branch
