### ISSUE TITLE
Add About us and complete it.

### ISSUE THREAD

**Issue by daniduthisum** [VishwaAmarasinghe/codeflow-website#18]
**Is your feature request related to a problem? Please describe.**
Add About us to display the details.
**Describe the solution you'd like**
Add section and details about our school

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
Can you assign me

**Comment by daniduthisum** [comment]
Ok sure

**Comment by VishwaAmarasinghe** [comment]
Thank you
