### ISSUE TITLE
Add history page.

### ISSUE THREAD

**Issue by daniduthisum** [VishwaAmarasinghe/codeflow-website#21]
**Is your feature request related to a problem? Please describe.**
Add History.html to add our history of the collage.

**Describe the solution you'd like**
Add history.html file

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by daniduthisum** [comment]
Ok sure.
