### ISSUE TITLE
Add navbar to navbar.html

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [VishwaAmarasinghe/codeflow-website#27]
**Is your feature request related to a problem? Please describe.**
To use navbar and footer multiply times we should add navbar and footer to another html files and link them with js code

**Describe the solution you'd like**
Make two html files called navbar.html, footer.html and link them with a code

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
@daniduthisum give me your idea

**Comment by daniduthisum** [comment]
Nice.
