### ISSUE TITLE
Add Html files

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [VishwaAmarasinghe/codeflow-website#3]
**Is your feature request related to a problem? Please describe.**
We should add new HTML files.

**Describe the solution you'd like**
Make some HTML tags and link them when we want.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by daniduthisum** [comment]
Can you assign me.

**Comment by VishwaAmarasinghe** [comment]
I decided to make new HTML files without making sections. So we can load pages separately .

**Comment by daniduthisum** [comment]
That's good

> I decided to make new HTML files without making sections. So we can load pages separately .
