### ISSUE TITLE
Add CSS and JS file to assets folder

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [VishwaAmarasinghe/codeflow-website#5]
**Is your feature request related to a problem? Please describe.**
We have to add our CSS and JS file to the assets folder. So we can make our project folder beautifully 

**Describe the solution you'd like**
Make an assets folder and add CSS and JS files to that.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by daniduthisum** [comment]
Shall i open this.

**Comment by daniduthisum** [comment]
Shall I work on this.

**Comment by VishwaAmarasinghe** [comment]
Sure
