### ISSUE TITLE
Complete the home page

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [VishwaAmarasinghe/codeflow-website#7]
**Is your feature request related to a problem? Please describe.**
Complete the home page to welcome others
**Describe the solution you'd like**
Add an image and text.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by VishwaAmarasinghe** [comment]
@daniduthisum shall I make changes .

**Comment by daniduthisum** [comment]
Ok sure.

**Comment by VishwaAmarasinghe** [comment]
Thanks
